/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface CoreMathInterface extends ethers.utils.Interface {
  functions: {
    "radiv(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "radiv",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "radiv", data: BytesLike): Result;

  events: {};
}

export class CoreMath extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: CoreMathInterface;

  functions: {
    radiv(
      dividend: BigNumberish,
      divisor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "radiv(uint256,uint256)"(
      dividend: BigNumberish,
      divisor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  radiv(
    dividend: BigNumberish,
    divisor: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "radiv(uint256,uint256)"(
    dividend: BigNumberish,
    divisor: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    radiv(
      dividend: BigNumberish,
      divisor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "radiv(uint256,uint256)"(
      dividend: BigNumberish,
      divisor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    radiv(
      dividend: BigNumberish,
      divisor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "radiv(uint256,uint256)"(
      dividend: BigNumberish,
      divisor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    radiv(
      dividend: BigNumberish,
      divisor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "radiv(uint256,uint256)"(
      dividend: BigNumberish,
      divisor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
