/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MedianSpacexInterface extends ethers.utils.Interface {
  functions: {
    "age()": FunctionFragment;
    "bar()": FunctionFragment;
    "bud(address)": FunctionFragment;
    "diss(address[])": FunctionFragment;
    "drop(address)": FunctionFragment;
    "kiss(address[])": FunctionFragment;
    "lift(address)": FunctionFragment;
    "oracle(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "peek()": FunctionFragment;
    "poke(tuple[])": FunctionFragment;
    "read()": FunctionFragment;
    "recover(uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setBar(uint256)": FunctionFragment;
    "slot(uint8)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "wat()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "age", values?: undefined): string;
  encodeFunctionData(functionFragment: "bar", values?: undefined): string;
  encodeFunctionData(functionFragment: "bud", values: [string]): string;
  encodeFunctionData(functionFragment: "diss", values: [string[]]): string;
  encodeFunctionData(functionFragment: "drop", values: [string]): string;
  encodeFunctionData(functionFragment: "kiss", values: [string[]]): string;
  encodeFunctionData(functionFragment: "lift", values: [string]): string;
  encodeFunctionData(functionFragment: "oracle", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "peek", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poke",
    values: [
      {
        value: BigNumberish;
        age: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      }[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "read", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recover",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBar",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "slot", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "wat", values?: undefined): string;

  decodeFunctionResult(functionFragment: "age", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bud", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "diss", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "drop", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kiss", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lift", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "peek", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poke", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "read", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recover", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wat", data: BytesLike): Result;

  events: {
    "LogMedianPrice(uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogMedianPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class MedianSpacex extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MedianSpacexInterface;

  functions: {
    age(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    "age()"(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    bar(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "bar()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    bud(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "bud(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "diss(address[])"(
      accounts: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "diss(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    drop(account: string, overrides?: Overrides): Promise<ContractTransaction>;

    "drop(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "kiss(address[])"(
      accounts: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "kiss(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    lift(account: string, overrides?: Overrides): Promise<ContractTransaction>;

    "lift(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    oracle(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "oracle(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    peek(overrides?: CallOverrides): Promise<{
      0: BigNumber;
      1: boolean;
    }>;

    "peek()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
      1: boolean;
    }>;

    poke(
      data: {
        value: BigNumberish;
        age: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "poke(tuple[])"(
      data: {
        value: BigNumberish;
        age: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    read(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "read()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    recover(
      val_: BigNumberish,
      age_: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "recover(uint256,uint256,uint8,bytes32,bytes32)"(
      val_: BigNumberish,
      age_: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    setBar(
      bar_: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setBar(uint256)"(
      bar_: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    slot(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "slot(uint8)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    wat(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "wat()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  age(overrides?: CallOverrides): Promise<number>;

  "age()"(overrides?: CallOverrides): Promise<number>;

  bar(overrides?: CallOverrides): Promise<BigNumber>;

  "bar()"(overrides?: CallOverrides): Promise<BigNumber>;

  bud(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "bud(address)"(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "diss(address[])"(
    accounts: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "diss(address)"(
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  drop(account: string, overrides?: Overrides): Promise<ContractTransaction>;

  "drop(address)"(
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "kiss(address[])"(
    accounts: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "kiss(address)"(
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  lift(account: string, overrides?: Overrides): Promise<ContractTransaction>;

  "lift(address)"(
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  oracle(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "oracle(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  peek(overrides?: CallOverrides): Promise<{
    0: BigNumber;
    1: boolean;
  }>;

  "peek()"(overrides?: CallOverrides): Promise<{
    0: BigNumber;
    1: boolean;
  }>;

  poke(
    data: {
      value: BigNumberish;
      age: BigNumberish;
      v: BigNumberish;
      r: BytesLike;
      s: BytesLike;
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "poke(tuple[])"(
    data: {
      value: BigNumberish;
      age: BigNumberish;
      v: BigNumberish;
      r: BytesLike;
      s: BytesLike;
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  read(overrides?: CallOverrides): Promise<BigNumber>;

  "read()"(overrides?: CallOverrides): Promise<BigNumber>;

  recover(
    val_: BigNumberish,
    age_: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "recover(uint256,uint256,uint8,bytes32,bytes32)"(
    val_: BigNumberish,
    age_: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  setBar(
    bar_: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setBar(uint256)"(
    bar_: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  slot(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "slot(uint8)"(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  wat(overrides?: CallOverrides): Promise<string>;

  "wat()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    age(overrides?: CallOverrides): Promise<number>;

    "age()"(overrides?: CallOverrides): Promise<number>;

    bar(overrides?: CallOverrides): Promise<BigNumber>;

    "bar()"(overrides?: CallOverrides): Promise<BigNumber>;

    bud(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "bud(address)"(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "diss(address[])"(
      accounts: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "diss(address)"(account: string, overrides?: CallOverrides): Promise<void>;

    drop(account: string, overrides?: CallOverrides): Promise<void>;

    "drop(address)"(account: string, overrides?: CallOverrides): Promise<void>;

    "kiss(address[])"(
      accounts: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "kiss(address)"(account: string, overrides?: CallOverrides): Promise<void>;

    lift(account: string, overrides?: CallOverrides): Promise<void>;

    "lift(address)"(account: string, overrides?: CallOverrides): Promise<void>;

    oracle(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "oracle(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    peek(overrides?: CallOverrides): Promise<{
      0: BigNumber;
      1: boolean;
    }>;

    "peek()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
      1: boolean;
    }>;

    poke(
      data: {
        value: BigNumberish;
        age: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "poke(tuple[])"(
      data: {
        value: BigNumberish;
        age: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    read(overrides?: CallOverrides): Promise<BigNumber>;

    "read()"(overrides?: CallOverrides): Promise<BigNumber>;

    recover(
      val_: BigNumberish,
      age_: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "recover(uint256,uint256,uint8,bytes32,bytes32)"(
      val_: BigNumberish,
      age_: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    setBar(bar_: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "setBar(uint256)"(
      bar_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    slot(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "slot(uint8)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    wat(overrides?: CallOverrides): Promise<string>;

    "wat()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    LogMedianPrice(val: null, age: null): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    age(overrides?: CallOverrides): Promise<BigNumber>;

    "age()"(overrides?: CallOverrides): Promise<BigNumber>;

    bar(overrides?: CallOverrides): Promise<BigNumber>;

    "bar()"(overrides?: CallOverrides): Promise<BigNumber>;

    bud(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "bud(address)"(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "diss(address[])"(
      accounts: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "diss(address)"(account: string, overrides?: Overrides): Promise<BigNumber>;

    drop(account: string, overrides?: Overrides): Promise<BigNumber>;

    "drop(address)"(account: string, overrides?: Overrides): Promise<BigNumber>;

    "kiss(address[])"(
      accounts: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "kiss(address)"(account: string, overrides?: Overrides): Promise<BigNumber>;

    lift(account: string, overrides?: Overrides): Promise<BigNumber>;

    "lift(address)"(account: string, overrides?: Overrides): Promise<BigNumber>;

    oracle(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "oracle(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    peek(overrides?: CallOverrides): Promise<BigNumber>;

    "peek()"(overrides?: CallOverrides): Promise<BigNumber>;

    poke(
      data: {
        value: BigNumberish;
        age: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "poke(tuple[])"(
      data: {
        value: BigNumberish;
        age: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    read(overrides?: CallOverrides): Promise<BigNumber>;

    "read()"(overrides?: CallOverrides): Promise<BigNumber>;

    recover(
      val_: BigNumberish,
      age_: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "recover(uint256,uint256,uint8,bytes32,bytes32)"(
      val_: BigNumberish,
      age_: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    setBar(bar_: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "setBar(uint256)"(
      bar_: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    slot(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "slot(uint8)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    wat(overrides?: CallOverrides): Promise<BigNumber>;

    "wat()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    age(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "age()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bar(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "bar()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bud(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "bud(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "diss(address[])"(
      accounts: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "diss(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    drop(account: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "drop(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "kiss(address[])"(
      accounts: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "kiss(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    lift(account: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "lift(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    oracle(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "oracle(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    peek(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "peek()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poke(
      data: {
        value: BigNumberish;
        age: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "poke(tuple[])"(
      data: {
        value: BigNumberish;
        age: BigNumberish;
        v: BigNumberish;
        r: BytesLike;
        s: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    read(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "read()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    recover(
      val_: BigNumberish,
      age_: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "recover(uint256,uint256,uint8,bytes32,bytes32)"(
      val_: BigNumberish,
      age_: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    setBar(
      bar_: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setBar(uint256)"(
      bar_: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    slot(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "slot(uint8)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    wat(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "wat()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
