/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { CoreMath } from "../CoreMath";

export class CoreMath__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<CoreMath> {
    return super.deploy(overrides || {}) as Promise<CoreMath>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): CoreMath {
    return super.attach(address) as CoreMath;
  }
  connect(signer: Signer): CoreMath__factory {
    return super.connect(signer) as CoreMath__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CoreMath {
    return new Contract(address, _abi, signerOrProvider) as CoreMath;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "dividend",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "divisor",
        type: "uint256",
      },
    ],
    name: "radiv",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610154806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063235e0cd814610030575b600080fd5b61004361003e3660046100a9565b610059565b60405161005091906100ca565b60405180910390f35b600061009661008461007e722cd76fe086b93ce2f768a00b22a00000000000866100f3565b8461009d565b6b033b2e3c9fd0803ce800000061009d565b9392505050565b600061009682846100d3565b600080604083850312156100bb578182fd5b50508035926020909101359150565b90815260200190565b6000826100ee57634e487b7160e01b81526012600452602481fd5b500490565b600081600019048311821515161561011957634e487b7160e01b81526011600452602481fd5b50029056fea26469706673582212201b81f8a2c32ec878f3f7d2cc56d0a59c7bb5a8e9cb725f43688aae9968772a2764736f6c63430008000033";
