export const TOKEN_NEUTRAL_COLOR_LOW_DARK = '#171717';
export const TOKEN_NEUTRAL_COLOR_LOW_LIGHT = '#333333';
export const TOKEN_NEUTRAL_COLOR_LOW_PURE = '#1e1e1e';

export const TOKEN_NEUTRAL_COLOR_HIGH_DARK = '#bdbdbd';
export const TOKEN_NEUTRAL_COLOR_HIGH_LIGHT = '#f2f2f2';
export const TOKEN_NEUTRAL_COLOR_HIGH_PURE = '#ffffff';

export const TOKEN_FEEDBACK_COLOR_POSITIVE_PURE = '#00f545';
export const TOKEN_FEEDBACK_COLOR_POSITIVE_DARK = '#0a1f15';

export const TOKEN_FEEDBACK_COLOR_NEGATIVE_PURE = '#f50041';
export const TOKEN_FEEDBACK_COLOR_NEGATIVE_DARK = '#330b08';

export const TOKEN_BACKGROUND_COLOR_DEFAULT = '#1e1e1e';

export const TOKEN_BRAND_COLOR_PRIMARY_PURE = '#EEFF00';
export const TOKEN_BRAND_COLOR_PRIMARY_DARK = '#3B2F12';

export const TOKEN_WARNING_COLOR_PRIMARY = '#EEFF00';
