name: Build and test on push
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Switch Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - name: Compile & test contracts
        run: yarn && npm run compile && npm run test
      # # - name: Run node & deploy contracts
      # #   run: npm run node & npm run deploy:local
      # - name: Test & build frontend
      #   run: cd frontend && npm i && CI=true npm test && npm run build
